[build]
  command = "npm install -g pnpm@10.30.3 --force && pnpm install && pnpm --filter client build"
  publish = "apps/client/.next"

[build.environment]
  NODE_VERSION = "20.20.1"
  PNPM_FLAGS = "--shamefully-hoist"

[[plugins]]
  package = "@netlify/plugin-nextjs"