import type { CardItem } from "@/components/common/Card/Card.types";

export const CATEGORIES = ["전체", "회화", "동양화", "한국화", "불교 미술"] as const;
export type Category = (typeof CATEGORIES)[number];

export const MOCK_ARTWORKS: Record<Category, CardItem[]> = {
	전체: [
		{
			id: 1,
			imageUrl: "/images/cups.png",
			title: "여백",
			category: "회화",
			author: "강승기",
		},
		{
			id: 5,
			imageUrl: "/images/plate.png",
			title: "산수",
			category: "동양화",
			author: "김민준",
		},
		{
			id: 9,
			imageUrl: "/images/pottery.png",
			title: "민화",
			category: "한국화",
			author: "정도윤",
		},
		{
			id: 13,
			imageUrl: "/images/pottery.png",
			title: "연화",
			category: "불교 미술",
			author: "한지수",
		},
		{
			id: 1,
			imageUrl: "/images/cups.png",
			title: "여백",
			category: "회화",
			author: "강승기",
		},
		{
			id: 5,
			imageUrl: "/images/plate.png",
			title: "산수",
			category: "동양화",
			author: "김민준",
		},
		{
			id: 9,
			imageUrl: "/images/pottery.png",
			title: "민화",
			category: "한국화",
			author: "정도윤",
		},
		{
			id: 13,
			imageUrl: "/images/pottery.png",
			title: "연화",
			category: "불교 미술",
			author: "한지수",
		},
	],
	회화: [
		{
			id: 1,
			imageUrl: "/images/cups.png",
			title: "여백",
			category: "회화",
			author: "강승기",
		},
		{
			id: 2,
			imageUrl: "/images/cups.png",
			title: "2000년 후",
			category: "회화",
			author: "배수향",
		},
		{
			id: 3,
			imageUrl: "/images/cups.png",
			title: "무한",
			category: "회화",
			author: "손수현",
		},
		{
			id: 4,
			imageUrl: "/images/cups.png",
			title: "1-0-8",
			category: "회화",
			author: "박수향",
		},
	],
	동양화: [
		{
			id: 5,
			imageUrl: "/images/plate.png",
			title: "산수",
			category: "동양화",
			author: "김민준",
		},
		{
			id: 6,
			imageUrl: "/images/plate.png",
			title: "춘하추동",
			category: "동양화",
			author: "이서연",
		},
		{
			id: 7,
			imageUrl: "/images/plate.png",
			title: "묵향",
			category: "동양화",
			author: "박지훈",
		},
		{
			id: 8,
			imageUrl: "/images/plate.png",
			title: "청풍",
			category: "동양화",
			author: "최수아",
		},
	],
	한국화: [
		{
			id: 9,
			imageUrl: "/images/pottery.png",
			title: "민화",
			category: "한국화",
			author: "정도윤",
		},
		{
			id: 10,
			imageUrl: "/images/pottery.png",
			title: "화조도",
			category: "한국화",
			author: "윤하은",
		},
		{
			id: 11,
			imageUrl: "/images/pottery.png",
			title: "책거리",
			category: "한국화",
			author: "임재원",
		},
		{
			id: 12,
			imageUrl: "/images/pottery.png",
			title: "봄날",
			category: "한국화",
			author: "강민서",
		},
	],
	"불교 미술": [
		{
			id: 13,
			imageUrl: "/images/pottery.png",
			title: "연화",
			category: "불교 미술",
			author: "한지수",
		},
		{
			id: 14,
			imageUrl: "/images/pottery.png",
			title: "법신",
			category: "불교 미술",
			author: "오승현",
		},
		{
			id: 15,
			imageUrl: "/images/pottery.png",
			title: "만다라",
			category: "불교 미술",
			author: "류채원",
		},
		{
			id: 16,
			imageUrl: "/images/pottery.png",
			title: "보리수",
			category: "불교 미술",
			author: "신예진",
		},
	],
};
